language: 
  node_js
node_js:
  - "stable" 
install:
  - npm install
  - npm install -g codecov
  - npm intsall -g istanbul
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
  - npm test